version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - "> 2.6.4"
  - dependency-name: eslint
    versions:
    - "> 7.32.0"
  - dependency-name: node-sass
    versions:
    - "> 6.0.1"
  - dependency-name: webpack
    versions:
    - "> 4.46.0"
